Add new Clojure & Functional Programming article
training-center/clojure-study-group pull request #20
Opened 2018-11-19 13:26 UTC by LeandroTk

Add the [An introduction to the basic principles of Functional Programming](https://medium.freecodecamp.org/an-introduction-to-the-basic-principles-of-functional-programming-a2c2a15c84) article to the `articles.md` file

2018-11-19 15:39 UTC, Diego-Brocanelli requested changes

2018-11-19 15:39 UTC, Diego-Brocanelli commented on material/dir/articles.md
> +- [An introduction to the basic principles of Functional Programming](https://medium.freecodecamp.org/an-introduction-to-the-basic-principles-of-functional-programming-a2c2a15c84)
Manter ordem alfabética da lista, para facilitar a localização dos itens.

2018-11-19 19:29 UTC, LeandroTk commented
@Diego-Brocanelli Coloquei os artigos em ordem alfabética

2018-11-19 19:44 UTC, LeandroTk commented
@Diego-Brocanelli Feito!

2018-11-19 20:44 UTC, LeandroTk commented
@Diego-Brocanelli Feito!
Mais algo que você acha que possa ser melhorado?

2018-11-20 11:17 UTC, Diego-Brocanelli approved these changes

2018-11-20 11:18 UTC, Diego-Brocanelli commented
Olá, @LeandroTk 

Obrigado pelas suas contribuições.

2018-11-20 11:18 UTC, merged